<header class="ui-widget ui-header ui-corner-all ui-state-default">
	<h1>gravity</h1>
	<button id="but-main-menu">main menu</button>
</header>

<div id="error" class="ui-widget ui-corner-all ui-state-error">
	<h3><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>An Error occurred:</h3>
	<p class="message"></p>
</div>

<div id="main-menu">
	<?php echo $this->mainMenu->toHtml(); ?>
</div>

<canvas id="viewport">your browser ain't support no canvas.</canvas>

<script src="lib/jquery-ui/js/jquery.min.js"></script>
<script src="lib/jquery-ui/js/jquery-ui.min.js"></script>

<?php echo $this->inlineScript() ?>